### ISSUE TITLE
[Bug] It does not work inside properties

### ISSUE THREAD

**Issue by anddns** [KraXen72/obsidian-emoji-autocomplete#4]
As the example below shows, it is possible to copy and paste emojis inside a property. However, the autocomplete feature does not work, and a short code does not turn into an emoji while the same properties are being edited. I think the short code detection system has a blind spot when it comes to a note's properties.

 It's strange because Obsidian notes are just plain text files, even the properties. The fancy interface is only there to match the current theme.

![simplescreenrecorder-2024-05-09_15 57 31](https://github.com/KraXen72/obsidian-emoji-autocomplete/assets/36433872/8b1f5698-6bee-4355-8d68-99ca4d60a49b)

**Comment by KraXen72** [comment]
sorry, but the properties core plugin only uses a `<div contenteditable></div>` instead of the proper editor like the rest of the file.
It's not possible to create a suggestion windows there. 
if you want to use the emoji autocomplete in the properties, use source mode (or set up a hotkey to toggle between source mode & live preview).
You could also use the system emoji picker or copy & paste the emoji in.
