### ISSUE TITLE
Let user change triggering character

### ISSUE THREAD

**Issue by Doggy-Footprint** [KraXen72/obsidian-emoji-autocomplete#5]
I'm enjoying your work with Obsidian for emojis. 

I tried to add a feature with which user can choose triggering character. 

That feature made few hardcoded variables of EmojiSuggester to be initialized in constructor. I think it's acceptable modifications for adding feature that dynamically determines the character to trigger EmojiSuggester.

But the problem is  emojiPostProcessor module.

I thought you separated this module for advantage in testing and debugging because Obsidian API doesn't officially supporting debugging tools. But to add the feature I thought, I think there is no way to avoid importing Obsidian dependent class in emojiPostProcessor module.

So, my question is

1. Is emojiPostProcessor module separed for debugging?
2. Is this project open for contribution?
3. If you are interested in adding feature to letting user to choose a charater to trigger suggestion, should emojiPostProcessor module be integrated?

![image](https://github.com/KraXen72/obsidian-emoji-autocomplete/assets/88776039/4b1db018-8117-4c27-a210-340a2526a5ad)

**Comment by KraXen72** [comment]
I don't quite understand the first question, but the emoji post processor module isn't really meant to be configurable - it just turns the shortcode form of emoji, like, `:heart:` into it's emoji equivalent: ❤️. I might reevaluate this later if given convincing arguments but for now, i think we should keep the configuration in the other parts of the plugin - the postprocessor is supposed to be a just works thing.

The project is open to contribution and I welcome any pull requests!

I think letting the user choose a trigger character is a good feature, but it shouldn't affect the emojiPostProcessor as I mentioned previously - there's no standard saying that `\heart\` should be considered an emoji. however, it makes much more sense with the immediate replace mode. it's more like a command, and I would make sense for the trigger character to be configurable.

As for EmojiPostProcessors separation, it's just so that different parts of the plugin that do different things are in separate files. I find it makes the code easier to maintain.

**Comment by Doggy-Footprint** [comment]
Don't mind the first question.

It's good to know that this project is open for contribution! 

I thought about this, and there is reasonable motivation to add the feature in expense of compromising EmojiPostProcessors separation. I agree that it should be separated from Obsidian.

Thanks.
